### ISSUE TITLE
Saving Schematic from negative position.

### ISSUE THREAD

**Issue by KrunkerPremium** [hollow-cube/common#44] opened 2023-05-06 22:33 UTC
Saving schematic from a negative position will cause the schematic to mess up the block order and dimentions.

for example.

this
![image](https://user-images.githubusercontent.com/128103081/236648848-7465d286-1cac-48f9-aa72-1bba8390b93a.png)
becomes this.
![image](https://user-images.githubusercontent.com/128103081/236648861-3a8de5bd-ba17-4297-ac25-c4bb63503029.png)

the problem seems to come from the SchematicBuilder but I might be wrong. The reader works perfectly for schematic that were not created on minestom.

my implementation.

                    PlayerClipboard playerClipboard = premiumAPI.getClipboard(p.getUuid());
                    Point pos1 = playerClipboard.getPos1();
                    Point pos2 = playerClipboard.getPos2();
                    playerClipboard.clear();
                    int startX = Math.min(pos1.blockX(), pos2.blockX());
                    int endX = Math.max(pos1.blockX(), pos2.blockX());
                    int startY = Math.min(pos1.blockY(), pos2.blockY());
                    int endY = Math.max(pos1.blockY(), pos2.blockY());
                    int startZ = Math.min(pos1.blockZ(), pos2.blockZ());
                    int endZ = Math.max(pos1.blockZ(), pos2.blockZ());

                    for (int y = startY; y <= endY; y++) {
                        for (int z = startZ; z <= endZ; z++) {
                            for (int x = startX; x <= endX; x++) {
                                Pos pos = new Pos(x, y, z);
                                playerClipboard.getBuilder().addBlock(pos, p.getInstance().getBlock(pos));
                            }
                        }
                    }
                    
                    //Pos offset = new Pos(pos1.blockX()-p.getPosition().blockX(),pos1.blockY()-p.getPosition().blockY(),pos1.blockZ()-p.getPosition().blockZ());

                    Schematic schematic = playerClipboard.getBuilder().build();
                    try {
                        File file = new File("./schematics/test.schem");
                        if (!file.exists()){
                            file.createNewFile();
                            p.sendMessage("Created New File");
                        }

                        SchematicWriter.write(schematic,file.toPath());
                        p.sendMessage("Success");
                    } catch (IOException e) {
                        p.sendMessage("Fail");
                        throw new RuntimeException(e);
                    }

**Comment by KrunkerPremium** [comment] 2023-05-06 22:34
I really hope im not stupid or anything but I can't seem to find the exact cause of this issue.

**Comment by mworzala** [comment] 2023-05-07 12:28
Well I have been trying to track down an issue with schematics ending up broken for a very long time, if this is it then I will be very excited :D ill look into it

**Comment by mworzala** [comment] 2023-05-07 13:02
This is fixed by the above commit. Im not completely sure this was the cause of my other issue, but it certainly was a glaring flaw.

Thanks for the report and detailed explanation/reproducer.

**Closed as completed** 2023-05-07 13:06 UTC
